name: Reuse SonarQube Python Workflow

on:
  workflow_run:
    workflows: ["Python run tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          
      - name: SQ Analysis
        uses: seanned/python-actions@main
        with:
          coverage-type: python
          coverage-path: coverage/coverage.xml
          sq-project: 'test-org-1qaz2wsx_python-test'
          sq-organization: 'test-org-1qaz2wsx'
          sq-token: ${{ secrets.SONAR_TOKEN }}
